version: '2'
services:
  api:
    build: .
    working_dir: /usr/src/app
    command: ./entrypoint.sh
    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - HTTP_PORT=3001
