version: '2'
services:
  apigateway:
    build: ./api-gateway/.
    command: npm start
    volumes:
      - ./api-gateway:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      HTTP_PORT: 3000
      SQUARE_SERVICE_URL: #
      TRIANGLE_SERVICE_URL: #

  squareservice:
    build: ./square-service/.
    command: npm start
    volumes:
      - ./square-service:/usr/src/app
    ports:
      - "3001:3001"
    environment:
      HTTP_PORT: 3001

  triangleservice:
    build: ./triangle-service/.
    command: npm start
    volumes:
      - ./triangle-service:/usr/src/app
    ports:
      - "3002:3002"
    environment:
      HTTP_PORT: 3002
