version: '2'
services:
  apigateway:
    build: ./api-gateway/.
    working_dir: /usr/src/app
    command: ./entrypoint.sh
    volumes:
      - ./api-gateway:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - squareservice
      - triangleservice
    links:
      - squareservice
      - triangleservice
    environment:
      HTTP_PORT: 3000
      SQUARE_SERVICE_URL: http://squareservice:3001
      TRIANGLE_SERVICE_URL: http://triangleservice:3002

  squareservice:
    build: ./square-service/.
    working_dir: /usr/src/app
    command: ./entrypoint.sh
    volumes:
      - ./square-service:/usr/src/app
    ports:
      - "3001:3001"
    environment:
      HTTP_PORT: 3001

  triangleservice:
    build: ./triangle-service/.
    working_dir: /usr/src/app
    command: ./entrypoint.sh
    volumes:
      - ./triangle-service:/usr/src/app
    ports:
      - "3002:3002"
    environment:
      HTTP_PORT: 3002
